### PR TITLE
fix: added pincode validation and corrected responsiveness of signup page.  

### LINKED ISSUE #796: [BUG] Adding Validation to pincode in Register as a User page
### Description

Validation of pincode length is already set in Register as NGO page, the same needs to be done in Register as a User page.

### Screenshots

image

### Browser 🥦

Microsoft Edge

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

### PR DESCRIPTION
**Pull request by Sar-thak-3**
Closes #796 

### Related Issue 

There was an issue with Pincode validation in the SignUp as User page. Also, there was a small issue of responsiveness (Video was attached below).

#### Changes made 👷🏻‍♂️
I fixed both of these issues. Kindly have a look.

### Videos 

https://github.com/tamalCodes/Milan/assets/100359818/6260261e-b191-4df5-a941-edbad9943808

### CODE REVIEW

**Comment by Sar-thak-3** [comment]
@tamalCodes I was not assigned yet on the issue but you told me to work on the issue. So now, I should delete this pull request or change title according to guidelines?

**Comment by tamalCodes** [comment]
> @tamalCodes I was not assigned yet on the issue but you told me to work on the issue. So now, I should delete this pull request or change title according to guidelines?

I told you to work on it which is fine by me, "assigning" does not make any difference TBH. 
I also told you to follow PR guidelines which means to have a proper PR title according to our docs. 
You can change the title of this PR itself, no need to make another !

File: src/pages/user/UserRegister.jsx [hunk 1]
```diff
@@ -52,7 +52,7 @@ const UserRegister = () => {
       email: { type: "string", format: "email" },
       password: { type: "string", minLength: 8 },
       address: { type: "string" },
-      pincode: { type: "number", pattern: "[0-9]+", minLength: 6 },
+      pincode: { type: "string", pattern: "[0-9]+", minLength: 6 , maxLength: 6},
```
Comment (tamalCodes) [inline src/pages/user/UserRegister.jsx:55]: I think the type should have been `number` as for most of the cases it is in number format.

**Review by tamalCodes — CHANGES_REQUESTED** [review]
Also when we are typing, we can actually input a lot of numbers for the pin code so it would be better if you could stop it at 6.

image


And with these changes I think we are good to merge.

File: src/pages/user/UserRegister.jsx (hunk 1 above)
Comment (Sar-thak-3) [reply src/pages/user/UserRegister.jsx:55]: If I change it to a number, two errors will be shown.

image

Pincode is not a valid value because of the datatype of pincode as passing it as "Number"  but to measure its length we need to send it as String!

If showing two errors works for you then I will make the changes. Kindly let me know.

Comment (tamalCodes) [reply src/pages/user/UserRegister.jsx]: @Sar-thak-3 , there should not be 2 errors obviously. 

At first You can put it in string and limit the input to 6. 
And if the value is within the range of 6 digits/char - convert it to a number of 6 digits and then push it to the DB.

**Comment by tamalCodes** [comment]
@Sar-thak-3 , if you have fixed the errors, do let me know and always click on the `resolve conversation` button.

**Review by tamalCodes — APPROVED** [review]
### Amazing work !
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/tamalCodes/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.
